//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationE.CRUDService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namField;
        
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string staField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string borField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nam {
            get {
                return this.namField;
            }
            set {
                if ((object.ReferenceEquals(this.namField, value) != true)) {
                    this.namField = value;
                    this.RaisePropertyChanged("nam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sta {
            get {
                return this.staField;
            }
            set {
                if ((object.ReferenceEquals(this.staField, value) != true)) {
                    this.staField = value;
                    this.RaisePropertyChanged("sta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bor {
            get {
                return this.borField;
            }
            set {
                if ((object.ReferenceEquals(this.borField, value) != true)) {
                    this.borField = value;
                    this.RaisePropertyChanged("bor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRUDService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  HelloWorldResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplicationE.CRUDService.HelloWorldResponse HelloWorld(WebApplicationE.CRUDService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.HelloWorldResponse> HelloWorldAsync(WebApplicationE.CRUDService.HelloWorldRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  BubbleSortResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BubbleSort", ReplyAction="*")]
        WebApplicationE.CRUDService.BubbleSortResponse BubbleSort(WebApplicationE.CRUDService.BubbleSortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BubbleSort", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.BubbleSortResponse> BubbleSortAsync(WebApplicationE.CRUDService.BubbleSortRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  FibResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fib", ReplyAction="*")]
        WebApplicationE.CRUDService.FibResponse Fib(WebApplicationE.CRUDService.FibRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fib", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.FibResponse> FibAsync(WebApplicationE.CRUDService.FibRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bmi", ReplyAction="*")]
        float Bmi(float kg, float m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bmi", ReplyAction="*")]
        System.Threading.Tasks.Task<float> BmiAsync(float kg, float m);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  empno 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpName", ReplyAction="*")]
        WebApplicationE.CRUDService.GetEmpNameResponse GetEmpName(WebApplicationE.CRUDService.GetEmpNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpName", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.GetEmpNameResponse> GetEmpNameAsync(WebApplicationE.CRUDService.GetEmpNameRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  DeleteNameResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteName", ReplyAction="*")]
        WebApplicationE.CRUDService.DeleteNameResponse DeleteName(WebApplicationE.CRUDService.DeleteNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteName", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.DeleteNameResponse> DeleteNameAsync(WebApplicationE.CRUDService.DeleteNameRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetAllDataResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllData", ReplyAction="*")]
        WebApplicationE.CRUDService.GetAllDataResponse GetAllData(WebApplicationE.CRUDService.GetAllDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.GetAllDataResponse> GetAllDataAsync(WebApplicationE.CRUDService.GetAllDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  nam 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewData", ReplyAction="*")]
        WebApplicationE.CRUDService.AddNewDataResponse AddNewData(WebApplicationE.CRUDService.AddNewDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.AddNewDataResponse> AddNewDataAsync(WebApplicationE.CRUDService.AddNewDataRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  nam 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        WebApplicationE.CRUDService.UpdateDataResponse UpdateData(WebApplicationE.CRUDService.UpdateDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.UpdateDataResponse> UpdateDataAsync(WebApplicationE.CRUDService.UpdateDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplicationE.CRUDService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplicationE.CRUDService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BubbleSortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BubbleSort", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.BubbleSortRequestBody Body;
        
        public BubbleSortRequest() {
        }
        
        public BubbleSortRequest(WebApplicationE.CRUDService.BubbleSortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BubbleSortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int A;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int B;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int C;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int D;
        
        public BubbleSortRequestBody() {
        }
        
        public BubbleSortRequestBody(int A, int B, int C, int D) {
            this.A = A;
            this.B = B;
            this.C = C;
            this.D = D;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BubbleSortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BubbleSortResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.BubbleSortResponseBody Body;
        
        public BubbleSortResponse() {
        }
        
        public BubbleSortResponse(WebApplicationE.CRUDService.BubbleSortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BubbleSortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BubbleSortResult;
        
        public BubbleSortResponseBody() {
        }
        
        public BubbleSortResponseBody(string BubbleSortResult) {
            this.BubbleSortResult = BubbleSortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fib", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.FibRequestBody Body;
        
        public FibRequest() {
        }
        
        public FibRequest(WebApplicationE.CRUDService.FibRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FibRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        public FibRequestBody() {
        }
        
        public FibRequestBody(int x) {
            this.x = x;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FibResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FibResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.FibResponseBody Body;
        
        public FibResponse() {
        }
        
        public FibResponse(WebApplicationE.CRUDService.FibResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FibResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FibResult;
        
        public FibResponseBody() {
        }
        
        public FibResponseBody(string FibResult) {
            this.FibResult = FibResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmpNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmpName", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.GetEmpNameRequestBody Body;
        
        public GetEmpNameRequest() {
        }
        
        public GetEmpNameRequest(WebApplicationE.CRUDService.GetEmpNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmpNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string empno;
        
        public GetEmpNameRequestBody() {
        }
        
        public GetEmpNameRequestBody(string empno) {
            this.empno = empno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmpNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmpNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.GetEmpNameResponseBody Body;
        
        public GetEmpNameResponse() {
        }
        
        public GetEmpNameResponse(WebApplicationE.CRUDService.GetEmpNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmpNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmpNameResult;
        
        public GetEmpNameResponseBody() {
        }
        
        public GetEmpNameResponseBody(string GetEmpNameResult) {
            this.GetEmpNameResult = GetEmpNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteName", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.DeleteNameRequestBody Body;
        
        public DeleteNameRequest() {
        }
        
        public DeleteNameRequest(WebApplicationE.CRUDService.DeleteNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteNameRequestBody() {
        }
        
        public DeleteNameRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.DeleteNameResponseBody Body;
        
        public DeleteNameResponse() {
        }
        
        public DeleteNameResponse(WebApplicationE.CRUDService.DeleteNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplicationE.CRUDService.Card[] DeleteNameResult;
        
        public DeleteNameResponseBody() {
        }
        
        public DeleteNameResponseBody(WebApplicationE.CRUDService.Card[] DeleteNameResult) {
            this.DeleteNameResult = DeleteNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllData", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.GetAllDataRequestBody Body;
        
        public GetAllDataRequest() {
        }
        
        public GetAllDataRequest(WebApplicationE.CRUDService.GetAllDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDataRequestBody {
        
        public GetAllDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.GetAllDataResponseBody Body;
        
        public GetAllDataResponse() {
        }
        
        public GetAllDataResponse(WebApplicationE.CRUDService.GetAllDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplicationE.CRUDService.Card[] GetAllDataResult;
        
        public GetAllDataResponseBody() {
        }
        
        public GetAllDataResponseBody(WebApplicationE.CRUDService.Card[] GetAllDataResult) {
            this.GetAllDataResult = GetAllDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewData", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.AddNewDataRequestBody Body;
        
        public AddNewDataRequest() {
        }
        
        public AddNewDataRequest(WebApplicationE.CRUDService.AddNewDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nam;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sta;
        
        public AddNewDataRequestBody() {
        }
        
        public AddNewDataRequestBody(int id, string nam, int age, string sta) {
            this.id = id;
            this.nam = nam;
            this.age = age;
            this.sta = sta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.AddNewDataResponseBody Body;
        
        public AddNewDataResponse() {
        }
        
        public AddNewDataResponse(WebApplicationE.CRUDService.AddNewDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplicationE.CRUDService.Card[] AddNewDataResult;
        
        public AddNewDataResponseBody() {
        }
        
        public AddNewDataResponseBody(WebApplicationE.CRUDService.Card[] AddNewDataResult) {
            this.AddNewDataResult = AddNewDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateData", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.UpdateDataRequestBody Body;
        
        public UpdateDataRequest() {
        }
        
        public UpdateDataRequest(WebApplicationE.CRUDService.UpdateDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nam;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sta;
        
        public UpdateDataRequestBody() {
        }
        
        public UpdateDataRequestBody(int id, string nam, int age, string sta) {
            this.id = id;
            this.nam = nam;
            this.age = age;
            this.sta = sta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationE.CRUDService.UpdateDataResponseBody Body;
        
        public UpdateDataResponse() {
        }
        
        public UpdateDataResponse(WebApplicationE.CRUDService.UpdateDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplicationE.CRUDService.Card[] UpdateDataResult;
        
        public UpdateDataResponseBody() {
        }
        
        public UpdateDataResponseBody(WebApplicationE.CRUDService.Card[] UpdateDataResult) {
            this.UpdateDataResult = UpdateDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplicationE.CRUDService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplicationE.CRUDService.WebService1Soap>, WebApplicationE.CRUDService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.HelloWorldResponse WebApplicationE.CRUDService.WebService1Soap.HelloWorld(WebApplicationE.CRUDService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplicationE.CRUDService.HelloWorldRequest inValue = new WebApplicationE.CRUDService.HelloWorldRequest();
            inValue.Body = new WebApplicationE.CRUDService.HelloWorldRequestBody();
            WebApplicationE.CRUDService.HelloWorldResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.HelloWorldResponse> WebApplicationE.CRUDService.WebService1Soap.HelloWorldAsync(WebApplicationE.CRUDService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.HelloWorldResponse> HelloWorldAsync() {
            WebApplicationE.CRUDService.HelloWorldRequest inValue = new WebApplicationE.CRUDService.HelloWorldRequest();
            inValue.Body = new WebApplicationE.CRUDService.HelloWorldRequestBody();
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.BubbleSortResponse WebApplicationE.CRUDService.WebService1Soap.BubbleSort(WebApplicationE.CRUDService.BubbleSortRequest request) {
            return base.Channel.BubbleSort(request);
        }
        
        public string BubbleSort(int A, int B, int C, int D) {
            WebApplicationE.CRUDService.BubbleSortRequest inValue = new WebApplicationE.CRUDService.BubbleSortRequest();
            inValue.Body = new WebApplicationE.CRUDService.BubbleSortRequestBody();
            inValue.Body.A = A;
            inValue.Body.B = B;
            inValue.Body.C = C;
            inValue.Body.D = D;
            WebApplicationE.CRUDService.BubbleSortResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).BubbleSort(inValue);
            return retVal.Body.BubbleSortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.BubbleSortResponse> WebApplicationE.CRUDService.WebService1Soap.BubbleSortAsync(WebApplicationE.CRUDService.BubbleSortRequest request) {
            return base.Channel.BubbleSortAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.BubbleSortResponse> BubbleSortAsync(int A, int B, int C, int D) {
            WebApplicationE.CRUDService.BubbleSortRequest inValue = new WebApplicationE.CRUDService.BubbleSortRequest();
            inValue.Body = new WebApplicationE.CRUDService.BubbleSortRequestBody();
            inValue.Body.A = A;
            inValue.Body.B = B;
            inValue.Body.C = C;
            inValue.Body.D = D;
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).BubbleSortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.FibResponse WebApplicationE.CRUDService.WebService1Soap.Fib(WebApplicationE.CRUDService.FibRequest request) {
            return base.Channel.Fib(request);
        }
        
        public string Fib(int x) {
            WebApplicationE.CRUDService.FibRequest inValue = new WebApplicationE.CRUDService.FibRequest();
            inValue.Body = new WebApplicationE.CRUDService.FibRequestBody();
            inValue.Body.x = x;
            WebApplicationE.CRUDService.FibResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).Fib(inValue);
            return retVal.Body.FibResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.FibResponse> WebApplicationE.CRUDService.WebService1Soap.FibAsync(WebApplicationE.CRUDService.FibRequest request) {
            return base.Channel.FibAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.FibResponse> FibAsync(int x) {
            WebApplicationE.CRUDService.FibRequest inValue = new WebApplicationE.CRUDService.FibRequest();
            inValue.Body = new WebApplicationE.CRUDService.FibRequestBody();
            inValue.Body.x = x;
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).FibAsync(inValue);
        }
        
        public float Bmi(float kg, float m) {
            return base.Channel.Bmi(kg, m);
        }
        
        public System.Threading.Tasks.Task<float> BmiAsync(float kg, float m) {
            return base.Channel.BmiAsync(kg, m);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.GetEmpNameResponse WebApplicationE.CRUDService.WebService1Soap.GetEmpName(WebApplicationE.CRUDService.GetEmpNameRequest request) {
            return base.Channel.GetEmpName(request);
        }
        
        public string GetEmpName(string empno) {
            WebApplicationE.CRUDService.GetEmpNameRequest inValue = new WebApplicationE.CRUDService.GetEmpNameRequest();
            inValue.Body = new WebApplicationE.CRUDService.GetEmpNameRequestBody();
            inValue.Body.empno = empno;
            WebApplicationE.CRUDService.GetEmpNameResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).GetEmpName(inValue);
            return retVal.Body.GetEmpNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.GetEmpNameResponse> WebApplicationE.CRUDService.WebService1Soap.GetEmpNameAsync(WebApplicationE.CRUDService.GetEmpNameRequest request) {
            return base.Channel.GetEmpNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.GetEmpNameResponse> GetEmpNameAsync(string empno) {
            WebApplicationE.CRUDService.GetEmpNameRequest inValue = new WebApplicationE.CRUDService.GetEmpNameRequest();
            inValue.Body = new WebApplicationE.CRUDService.GetEmpNameRequestBody();
            inValue.Body.empno = empno;
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).GetEmpNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.DeleteNameResponse WebApplicationE.CRUDService.WebService1Soap.DeleteName(WebApplicationE.CRUDService.DeleteNameRequest request) {
            return base.Channel.DeleteName(request);
        }
        
        public WebApplicationE.CRUDService.Card[] DeleteName(int id) {
            WebApplicationE.CRUDService.DeleteNameRequest inValue = new WebApplicationE.CRUDService.DeleteNameRequest();
            inValue.Body = new WebApplicationE.CRUDService.DeleteNameRequestBody();
            inValue.Body.id = id;
            WebApplicationE.CRUDService.DeleteNameResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).DeleteName(inValue);
            return retVal.Body.DeleteNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.DeleteNameResponse> WebApplicationE.CRUDService.WebService1Soap.DeleteNameAsync(WebApplicationE.CRUDService.DeleteNameRequest request) {
            return base.Channel.DeleteNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.DeleteNameResponse> DeleteNameAsync(int id) {
            WebApplicationE.CRUDService.DeleteNameRequest inValue = new WebApplicationE.CRUDService.DeleteNameRequest();
            inValue.Body = new WebApplicationE.CRUDService.DeleteNameRequestBody();
            inValue.Body.id = id;
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).DeleteNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.GetAllDataResponse WebApplicationE.CRUDService.WebService1Soap.GetAllData(WebApplicationE.CRUDService.GetAllDataRequest request) {
            return base.Channel.GetAllData(request);
        }
        
        public WebApplicationE.CRUDService.Card[] GetAllData() {
            WebApplicationE.CRUDService.GetAllDataRequest inValue = new WebApplicationE.CRUDService.GetAllDataRequest();
            inValue.Body = new WebApplicationE.CRUDService.GetAllDataRequestBody();
            WebApplicationE.CRUDService.GetAllDataResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).GetAllData(inValue);
            return retVal.Body.GetAllDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.GetAllDataResponse> WebApplicationE.CRUDService.WebService1Soap.GetAllDataAsync(WebApplicationE.CRUDService.GetAllDataRequest request) {
            return base.Channel.GetAllDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.GetAllDataResponse> GetAllDataAsync() {
            WebApplicationE.CRUDService.GetAllDataRequest inValue = new WebApplicationE.CRUDService.GetAllDataRequest();
            inValue.Body = new WebApplicationE.CRUDService.GetAllDataRequestBody();
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).GetAllDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.AddNewDataResponse WebApplicationE.CRUDService.WebService1Soap.AddNewData(WebApplicationE.CRUDService.AddNewDataRequest request) {
            return base.Channel.AddNewData(request);
        }
        
        public WebApplicationE.CRUDService.Card[] AddNewData(int id, string nam, int age, string sta) {
            WebApplicationE.CRUDService.AddNewDataRequest inValue = new WebApplicationE.CRUDService.AddNewDataRequest();
            inValue.Body = new WebApplicationE.CRUDService.AddNewDataRequestBody();
            inValue.Body.id = id;
            inValue.Body.nam = nam;
            inValue.Body.age = age;
            inValue.Body.sta = sta;
            WebApplicationE.CRUDService.AddNewDataResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).AddNewData(inValue);
            return retVal.Body.AddNewDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.AddNewDataResponse> WebApplicationE.CRUDService.WebService1Soap.AddNewDataAsync(WebApplicationE.CRUDService.AddNewDataRequest request) {
            return base.Channel.AddNewDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.AddNewDataResponse> AddNewDataAsync(int id, string nam, int age, string sta) {
            WebApplicationE.CRUDService.AddNewDataRequest inValue = new WebApplicationE.CRUDService.AddNewDataRequest();
            inValue.Body = new WebApplicationE.CRUDService.AddNewDataRequestBody();
            inValue.Body.id = id;
            inValue.Body.nam = nam;
            inValue.Body.age = age;
            inValue.Body.sta = sta;
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).AddNewDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationE.CRUDService.UpdateDataResponse WebApplicationE.CRUDService.WebService1Soap.UpdateData(WebApplicationE.CRUDService.UpdateDataRequest request) {
            return base.Channel.UpdateData(request);
        }
        
        public WebApplicationE.CRUDService.Card[] UpdateData(int id, string nam, int age, string sta) {
            WebApplicationE.CRUDService.UpdateDataRequest inValue = new WebApplicationE.CRUDService.UpdateDataRequest();
            inValue.Body = new WebApplicationE.CRUDService.UpdateDataRequestBody();
            inValue.Body.id = id;
            inValue.Body.nam = nam;
            inValue.Body.age = age;
            inValue.Body.sta = sta;
            WebApplicationE.CRUDService.UpdateDataResponse retVal = ((WebApplicationE.CRUDService.WebService1Soap)(this)).UpdateData(inValue);
            return retVal.Body.UpdateDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationE.CRUDService.UpdateDataResponse> WebApplicationE.CRUDService.WebService1Soap.UpdateDataAsync(WebApplicationE.CRUDService.UpdateDataRequest request) {
            return base.Channel.UpdateDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationE.CRUDService.UpdateDataResponse> UpdateDataAsync(int id, string nam, int age, string sta) {
            WebApplicationE.CRUDService.UpdateDataRequest inValue = new WebApplicationE.CRUDService.UpdateDataRequest();
            inValue.Body = new WebApplicationE.CRUDService.UpdateDataRequestBody();
            inValue.Body.id = id;
            inValue.Body.nam = nam;
            inValue.Body.age = age;
            inValue.Body.sta = sta;
            return ((WebApplicationE.CRUDService.WebService1Soap)(this)).UpdateDataAsync(inValue);
        }
    }
}
